name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      WORKFLOW_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install

      - name: Build the application
        run: pnpm run build

      - name: Configure Git
        run: |
          git config --global user.name "LZygmunt Bot"
          git config --global user.email "lzygmuntbot@user.noreply.github.com"

      - name: Add dist folder
        run: git add -f dist

      - name: Commit changes
        run: git commit -m "Add build artifacts"

      - name: Push to build branch
        run: |
          git remote set-url origin https://x-access-token:${WORKFLOW_TOKEN}@github.com/${{ github.repository }}.git
          git push -f origin HEAD:build
