name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: pnpm install

      - name: Build the application
        run: pnpm run build

      - name: Configure Git
        run: |
          git config --global user.name "LZygmunt Bot"
          git config --global user.email "lzygmuntbot@user.noreply.github.com"

      - name: Add dist folder
        run: git add -f dist

      - name: Commit changes
        run: git commit -m "Add build artifacts"

      - name: Push to build branch
        run: git push -f origin HEAD:build
